name : AndroidBuild
on :
  pull_request:
    branches: [features/repository]
  push:
    branches: [features/repository]
jobs :
    build :
      runs-on : ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Java JDK
          uses: actions/setup-java@v4.5.0
          with:
            java-version: '11'
            distribution: 'adopt'

        - name: Build with Gradle
          run: ./gradlew build

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.4.3
          with:
            name : CloudMate.apk
            path : app/build/outputs/apk/debug/app-debug.apk