name: AndroidBuild
on:
  pull_request:
    branches:
      - develop
      - master
      - features/repository
  push:
    branches:
      - develop
      - master
      - features/repository
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Bước 1: Kiểm tra mã nguồn
      - name: Checkout
        uses: actions/checkout@v4

      # Bước 2: Thiết lập môi trường Java
      - name: Set up Java 17 for Gradle runtime
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'adopt'

      # Bước 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Bước 4: Phân quyền Gradle Wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Bước 5: Chạy kiểm tra định dạng mã nguồn
      - name: Run Lint Check
        run: ./gradlew lint

      # Bước 6: Thiết lập môi trường Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

        # Bước 7: Khởi động Emulator
      - name: Start Emulator
        run: |
          echo "Available AVDs:"
           $ANDROID_HOME/emulator/emulator -list-avds
          nohup emulator -avd "Medium Phone API 35" -no-snapshot-save -no-window -gpu off > /dev/null 2>&1 &
          sleep 90
          adb devices
          adb wait-for-device
          adb shell input keyevent 82

      # Bước 8: Kiểm thử đơn vị
      - name: Run Unit Tests
        run: ./gradlew test

      # Bước 9: Lưu báo cáo kiểm thử đơn vị
      - name: Upload Unit Test Reports
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Unit-Test-Report
          path: build/reports/tests/testDebugUnitTest/

      # Bước 10: Kiểm thử giao diện
      - name: Run UI Tests
        run: ./gradlew connectedAndroidTest

      # Bước 11: Lưu báo cáo kiểm thử giao diện
      - name: Upload UI Test Reports
        uses: actions/upload-artifact@v4.4.3
        with:
          name: UI-Test-Report
          path: app/build/reports/androidTests/connected/

      # Bước 12: Build ứng dụng
      - name: Build APK
        run: ./gradlew assembleDebug

      # Bước 13: Tải lên file APK
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: CloudMate-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # Bước 14: Ghi log kết quả ra console
      - name: Log Test Results
        if: always()
        run: |
          echo "======================== Build and Test Results ========================"
          echo "Workflow Status: ${{ job.status }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run Link: ${{ github.run_url }}"
          echo "======================================================================="
