name : AndroidBuild
on :
  pull_request:
    branches: [develop,master]
  push:
    branches: [develop,master]
jobs :
    build :
      runs-on : ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Java 17 for Gradle runtime
          uses: actions/setup-java@v4.5.0
          with:
              java-version: '17'
              distribution: 'adopt'

        - name: Grant execute permission for gradlew
          run: chmod +x ./gradlew

        - name: Build with Gradle
          run: ./gradlew build

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.4.3
          with:
            name : CloudMate.apk
            path : app/build/outputs/apk/debug/app-debug.apk