name: AndroidTest
on:
  pull_request:
    branches: [features/repository]
  push:
    branches: [features/repository]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17 for Gradle runtime
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Upload Unit Test Reports
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Unit-Test-Report
          path: build/reports/tests/testDebugUnitTest/

      - name: Run UI Tests
        run: ./gradlew connectedAndroidTest

      - name: Upload UI Test Reports
        uses: actions/upload-artifact@v4.4.3
        with:
          name: UI-Test-Report
          path: app/build/reports/androidTests/connected/
